-- This module is the root of the BatemanHornConjectureCanonicalLaneLean Lean proof package.
import BatemanHornConjectureCanonicalLaneLean.Basic
import BatemanHornConjectureCanonicalLaneLean.SourcePackage
import BatemanHornConjectureCanonicalLaneLean.SourceDependencies
import BatemanHornConjectureCanonicalLaneLean.Formalization
import BatemanHornConjectureCanonicalLaneLean.ReviewerBridge
import BatemanHornConjectureCanonicalLaneLean.TheoremStatement
import BatemanHornConjectureCanonicalLaneLean.MathlibObjects
import BatemanHornConjectureCanonicalLaneLean.AdmissibleClass
import BatemanHornConjectureCanonicalLaneLean.Projection
import BatemanHornConjectureCanonicalLaneLean.BridgeLemmas
import BatemanHornConjectureCanonicalLaneLean.GateLemmas
import BatemanHornConjectureCanonicalLaneLean.FinalTheorem
import BatemanHornConjectureCanonicalLaneLean.MathlibStatement
